server:
  port: 9090

---
spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
logging:
  config: classpath:config/logback-spring-local.xml

# 개발 환경
---
spring:
  profiles: dev
logging:
  config: classpath:config/logback-spring-dev.xml
